### ISSUE TITLE
Support/Adopt InverseFunctions?

### ISSUE THREAD

**Issue by oschulz** [JuliaML/TransformsBase.jl#15]
[InverseFunctions](`https://github.com/JuliaMath/InverseFunctions.jl`) is a lightweight central package that defines an `inverse(f)` API. Would be the interest in adopting/supporting it in TransformsBase?

**Comment by juliohm** [comment]
I think we considered it in the past. It seems that the transforms here
don't satisfy the requirements of the InverseFunctions.jl API.

Em sáb., 17 de ago. de 2024, 07:00, Oliver Schulz ***@***.***>
escreveu:

**Comment by oschulz** [comment]
Ah, thanks @juliohm !

**Comment by juliohm** [comment]
The Functional transform in TableTransforms.jl uses the InverseFunctions.jl
API. Might be of your interest.

Em sáb., 17 de ago. de 2024, 11:55, Oliver Schulz ***@***.***>
escreveu:

**Comment by oschulz** [comment]
Oh yes, neat! Just curious, in what way does `TransformsBase.inverse` not fulfill the requirement of `InverseFunctions.inverse` (and might we need to widen the scope in InverseFunctions for such cases)?

**Comment by juliohm** [comment]
If I recall it correctly, the docstrings mention properties such as
inv(f)(f(x)) == x

We support approximate equality sometimes. Don't remember other issues out
of my head.

Em sáb., 17 de ago. de 2024, 17:56, Oliver Schulz ***@***.***>
escreveu:

**Comment by oschulz** [comment]
Oh, approximate equality is perfectly fine for InverseFunction!

**Comment by juliohm** [comment]
@eliascarv do you remember any other issue we encountered in this context?

**Comment by eliascarv** [comment]
The `InverseFunctions` API is not used here because of incompatibility between the designs. The `TransformsBase.isinvertible` function that checks whether a transform is invertible has a fallback implemented with the transform type, while the `InverseFunctions.hasinverse` function that would be used in this fallback only works with instances and not with types.

**Comment by oschulz** [comment]
Thanks for the explanation @eliascarv !
