### ISSUE TITLE
Add equality test for SequentialTransform

### ISSUE THREAD

**Issue by VEZY** [JuliaML/TransformsBase.jl#8]
testing equality between transformations works just fine, but not when we test for two `SequentialTransform`. Using Meshes for the example:

```julia
t1 = Meshes.Affine([-0.1 8.7 0.5; -1.5 -0.1 4.3; 0.1 1.9 0.0], [0.0, 0.0, 0.0]) → Meshes.Translate(0.0, 0.0, 0.0)
t2 = Meshes.Affine([-0.1 8.7 0.5; -1.5 -0.1 4.3; 0.1 1.9 0.0], [0.0, 0.0, 0.0]) → Meshes.Translate(0.0, 0.0, 0.0)

t1 == t2
```

But if we do this it works:

```julia
t1.transforms == t2.transforms
```

Would it be possible to add a method for Base for testing equality like this?

**Comment by juliohm** [comment]
Thanks for reporting the issue @VEZY. Will work on it.

**Comment by juliohm** [comment]
@VEZY feel free to submit a PR for review. We are currently a bit busy in other parts of the stack. If you submit the PR, we can quickly review, merge and release a patch.

**Comment by VEZY** [comment]
Will do!

**Comment by juliohm** [comment]
Fixed on master.
